version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=to-do-no
      - POSTGRES_USER=fabricio
      - POSTGRES_PASSWORD=Fabricio112358
    ports:
      - 5433:5432
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"